/* The following code was generated by JFlex 1.6.1 */

package c;

import beaver.Symbol;

import c.Parser.Terminals;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/home/unimelb.edu.au/gernst/workspace/beaver-c/src/c/Scanner.flex</tt>
 */
class Scanner extends beaver.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\2\1\1\1\4\1\1\1\1\22\0\1\2\1\22\3\0"+
    "\1\32\1\35\1\0\1\10\1\11\1\7\1\16\1\42\1\17\1\20"+
    "\1\3\12\66\1\41\1\43\1\33\1\34\1\21\1\40\1\0\13\65"+
    "\1\6\1\65\1\5\14\65\1\12\1\0\1\13\1\36\1\65\1\0"+
    "\1\50\1\62\1\46\1\45\1\27\1\31\1\55\1\47\1\25\1\65"+
    "\1\63\1\54\1\57\1\53\1\30\1\61\1\65\1\51\1\24\1\52"+
    "\1\56\1\44\1\64\1\65\1\60\1\26\1\14\1\37\1\15\1\23"+
    "\6\0\1\4\u1fa2\0\1\4\1\4\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\4\4\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\11\4\1\34\2\0"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\3\4"+
    "\1\44\4\4\1\45\1\46\1\47\1\50\1\51\1\4"+
    "\1\52\10\4\3\0\4\4\1\53\2\4\1\54\12\4"+
    "\1\2\1\0\1\2\4\4\1\55\1\56\1\57\1\4"+
    "\1\60\2\4\1\61\6\4\1\62\5\4\1\63\1\64"+
    "\1\65\1\66\1\67\1\70\1\4\1\71\3\4\1\72"+
    "\1\4\1\73\1\74";

  private static int [] zzUnpackAction() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\334\0\u0113\0\67\0\67"+
    "\0\67\0\67\0\67\0\67\0\u014a\0\u0181\0\67\0\u01b8"+
    "\0\u01ef\0\67\0\u0226\0\u025d\0\u0294\0\u02cb\0\u0113\0\u0302"+
    "\0\u0339\0\u0370\0\u0113\0\u03a7\0\67\0\67\0\67\0\67"+
    "\0\u03de\0\u0415\0\u044c\0\u0483\0\u04ba\0\u04f1\0\u0528\0\u055f"+
    "\0\u0596\0\u05cd\0\u0604\0\u063b\0\67\0\67\0\67\0\67"+
    "\0\u0113\0\67\0\67\0\u0672\0\u06a9\0\u06e0\0\334\0\u0717"+
    "\0\u074e\0\u0785\0\u07bc\0\u0113\0\67\0\67\0\67\0\67"+
    "\0\u07f3\0\334\0\u082a\0\u0861\0\u0898\0\u08cf\0\u0906\0\u093d"+
    "\0\u0974\0\u09ab\0\u09e2\0\u0a19\0\u0a50\0\u0a87\0\u0abe\0\u0af5"+
    "\0\u0b2c\0\334\0\u0b63\0\u0b9a\0\334\0\u0bd1\0\u0c08\0\u0c3f"+
    "\0\u0c76\0\u0cad\0\u0ce4\0\u0d1b\0\u0d52\0\u0d89\0\u0dc0\0\u0604"+
    "\0\u0df7\0\67\0\u0e2e\0\u0e65\0\u0e9c\0\u0ed3\0\334\0\334"+
    "\0\334\0\u0f0a\0\334\0\u0f41\0\u0f78\0\334\0\u0faf\0\u0fe6"+
    "\0\u101d\0\u1054\0\u108b\0\u10c2\0\334\0\u10f9\0\u1130\0\u1167"+
    "\0\u119e\0\u11d5\0\334\0\334\0\334\0\334\0\334\0\334"+
    "\0\u120c\0\334\0\u1243\0\u127a\0\u12b1\0\334\0\u12e8\0\334"+
    "\0\334";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\2\2\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\5\1\25\1\5\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\2\5\1\44\1\45"+
    "\1\5\1\46\1\5\1\47\3\5\1\50\1\5\1\51"+
    "\1\5\1\52\70\0\2\3\67\0\1\53\3\0\1\54"+
    "\24\0\1\55\37\0\2\5\15\0\6\5\12\0\23\5"+
    "\34\0\1\55\50\0\1\56\15\0\1\55\51\0\1\57"+
    "\1\0\1\60\12\0\1\55\53\0\1\61\12\0\1\62"+
    "\66\0\1\63\37\0\2\5\15\0\1\5\1\64\4\5"+
    "\12\0\3\5\1\65\2\5\1\66\14\5\5\0\2\5"+
    "\15\0\5\5\1\67\12\0\7\5\1\70\13\5\5\0"+
    "\2\5\15\0\6\5\12\0\7\5\1\71\1\72\12\5"+
    "\5\0\2\5\15\0\4\5\1\73\1\5\12\0\23\5"+
    "\33\0\1\74\1\75\66\0\1\76\66\0\1\55\1\77"+
    "\65\0\1\55\2\0\1\100\34\0\2\5\15\0\4\5"+
    "\1\101\1\5\12\0\23\5\5\0\2\5\15\0\4\5"+
    "\1\102\1\5\12\0\23\5\5\0\2\5\15\0\4\5"+
    "\1\103\1\5\12\0\3\5\1\104\17\5\5\0\2\5"+
    "\15\0\3\5\1\105\2\5\12\0\23\5\5\0\2\5"+
    "\15\0\6\5\12\0\14\5\1\106\6\5\5\0\2\5"+
    "\15\0\4\5\1\107\1\5\12\0\23\5\5\0\2\5"+
    "\15\0\6\5\12\0\7\5\1\110\13\5\5\0\2\5"+
    "\15\0\6\5\12\0\5\5\1\111\15\5\5\0\2\5"+
    "\15\0\6\5\12\0\3\5\1\112\17\5\66\0\1\52"+
    "\1\53\1\0\2\53\1\0\1\113\61\53\7\114\1\115"+
    "\57\114\5\0\2\5\15\0\2\5\1\116\3\5\12\0"+
    "\11\5\1\117\11\5\5\0\2\5\15\0\4\5\1\120"+
    "\1\5\12\0\23\5\5\0\2\5\15\0\6\5\12\0"+
    "\5\5\1\121\15\5\5\0\2\5\15\0\6\5\12\0"+
    "\6\5\1\122\14\5\5\0\2\5\15\0\6\5\12\0"+
    "\12\5\1\123\10\5\5\0\2\5\15\0\1\124\5\5"+
    "\12\0\23\5\5\0\2\5\15\0\6\5\12\0\5\5"+
    "\1\125\15\5\5\0\2\5\15\0\1\5\1\126\4\5"+
    "\12\0\23\5\5\0\2\5\15\0\6\5\12\0\7\5"+
    "\1\127\13\5\5\0\2\5\15\0\6\5\12\0\4\5"+
    "\1\130\16\5\5\0\2\5\15\0\6\5\12\0\6\5"+
    "\1\131\14\5\5\0\2\5\15\0\6\5\12\0\15\5"+
    "\1\132\5\5\5\0\2\5\15\0\6\5\12\0\7\5"+
    "\1\133\13\5\5\0\2\5\15\0\1\134\1\135\4\5"+
    "\12\0\23\5\5\0\2\5\15\0\3\5\1\136\2\5"+
    "\12\0\23\5\5\0\2\5\15\0\1\5\1\137\4\5"+
    "\12\0\23\5\1\53\1\0\2\53\1\0\1\113\1\140"+
    "\60\53\7\114\1\141\57\114\3\0\1\142\3\0\1\115"+
    "\64\0\2\5\15\0\3\5\1\143\2\5\12\0\23\5"+
    "\5\0\2\5\15\0\6\5\12\0\7\5\1\144\13\5"+
    "\5\0\2\5\15\0\6\5\12\0\5\5\1\145\15\5"+
    "\5\0\2\5\15\0\6\5\12\0\12\5\1\146\10\5"+
    "\5\0\2\5\15\0\6\5\12\0\13\5\1\147\7\5"+
    "\5\0\2\5\15\0\3\5\1\150\2\5\12\0\23\5"+
    "\5\0\2\5\15\0\6\5\12\0\1\5\1\151\21\5"+
    "\5\0\2\5\15\0\6\5\12\0\6\5\1\152\14\5"+
    "\5\0\2\5\15\0\6\5\12\0\5\5\1\153\15\5"+
    "\5\0\2\5\15\0\6\5\12\0\12\5\1\154\10\5"+
    "\5\0\2\5\15\0\3\5\1\155\2\5\12\0\23\5"+
    "\5\0\2\5\15\0\6\5\12\0\11\5\1\156\11\5"+
    "\5\0\2\5\15\0\1\5\1\157\4\5\12\0\23\5"+
    "\5\0\2\5\15\0\4\5\1\160\1\5\12\0\23\5"+
    "\5\0\2\5\15\0\6\5\12\0\4\5\1\161\16\5"+
    "\5\0\2\5\15\0\6\5\12\0\10\5\1\162\12\5"+
    "\3\114\1\142\3\114\1\141\57\114\5\0\2\5\15\0"+
    "\4\5\1\163\1\5\12\0\23\5\5\0\2\5\15\0"+
    "\3\5\1\164\2\5\12\0\23\5\5\0\2\5\15\0"+
    "\6\5\12\0\6\5\1\165\14\5\5\0\2\5\15\0"+
    "\6\5\12\0\2\5\1\166\20\5\5\0\2\5\15\0"+
    "\1\5\1\167\4\5\12\0\23\5\5\0\2\5\15\0"+
    "\6\5\12\0\5\5\1\170\15\5\5\0\2\5\15\0"+
    "\6\5\12\0\1\5\1\171\21\5\5\0\2\5\15\0"+
    "\6\5\12\0\11\5\1\172\11\5\5\0\2\5\15\0"+
    "\6\5\12\0\7\5\1\173\13\5\5\0\2\5\15\0"+
    "\6\5\12\0\17\5\1\174\3\5\5\0\2\5\15\0"+
    "\3\5\1\175\2\5\12\0\23\5\5\0\2\5\15\0"+
    "\5\5\1\176\12\0\23\5\5\0\2\5\15\0\6\5"+
    "\12\0\1\5\1\177\21\5\5\0\2\5\15\0\6\5"+
    "\12\0\6\5\1\200\14\5\5\0\2\5\15\0\6\5"+
    "\12\0\7\5\1\201\13\5\5\0\2\5\15\0\6\5"+
    "\12\0\7\5\1\202\13\5\5\0\2\5\15\0\3\5"+
    "\1\203\2\5\12\0\23\5\5\0\2\5\15\0\6\5"+
    "\12\0\7\5\1\204\13\5\5\0\2\5\15\0\6\5"+
    "\12\0\12\5\1\205\10\5\5\0\2\5\15\0\5\5"+
    "\1\206\12\0\23\5\5\0\2\5\15\0\3\5\1\207"+
    "\2\5\12\0\23\5\5\0\2\5\15\0\3\5\1\210"+
    "\2\5\12\0\23\5\5\0\2\5\15\0\6\5\12\0"+
    "\1\5\1\211\21\5";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4895];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\6\11\2\1\1\11\2\1\1\11"+
    "\12\1\4\11\12\1\2\0\4\11\1\1\2\11\11\1"+
    "\4\11\12\1\3\0\23\1\1\0\1\11\47\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    Context context;

    Symbol resolve(String name) {
    	if(context.isType(name))
    		return new Symbol(Terminals.TYPE, yyline + 1, yycolumn + 1, name);
    	else
    		return new Symbol(Terminals.ID, yyline + 1, yycolumn + 1, name);
    }

	Symbol newToken(short id)
	{
		return new Symbol(id, yyline + 1, yycolumn + 1, yylength());
	}

	Symbol newToken(short id, Object value)
	{
		return new Symbol(id, yyline + 1, yycolumn + 1, yylength(), value);
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 184) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol nextToken() throws java.io.IOException, Scanner.Exception {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          { 	return newToken(Terminals.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Scanner.Exception("unexpected character '" + yytext() + "'");
            }
          case 61: break;
          case 2: 
            { 
            }
          case 62: break;
          case 3: 
            { return newToken(Terminals.DIV);
            }
          case 63: break;
          case 4: 
            { return resolve(yytext());
            }
          case 64: break;
          case 5: 
            { return newToken(Terminals.STAR);
            }
          case 65: break;
          case 6: 
            { return newToken(Terminals.LPAREN);
            }
          case 66: break;
          case 7: 
            { return newToken(Terminals.RPAREN);
            }
          case 67: break;
          case 8: 
            { return newToken(Terminals.LBRACK);
            }
          case 68: break;
          case 9: 
            { return newToken(Terminals.RBRACK);
            }
          case 69: break;
          case 10: 
            { return newToken(Terminals.LBRACE);
            }
          case 70: break;
          case 11: 
            { return newToken(Terminals.RBRACE);
            }
          case 71: break;
          case 12: 
            { return newToken(Terminals.PLUS);
            }
          case 72: break;
          case 13: 
            { return newToken(Terminals.MINUS);
            }
          case 73: break;
          case 14: 
            { return newToken(Terminals.DOT);
            }
          case 74: break;
          case 15: 
            { return newToken(Terminals.GT);
            }
          case 75: break;
          case 16: 
            { return newToken(Terminals.BANG);
            }
          case 76: break;
          case 17: 
            { return newToken(Terminals.TILDE);
            }
          case 77: break;
          case 18: 
            { return newToken(Terminals.MOD);
            }
          case 78: break;
          case 19: 
            { return newToken(Terminals.LT);
            }
          case 79: break;
          case 20: 
            { return newToken(Terminals.ASG);
            }
          case 80: break;
          case 21: 
            { return newToken(Terminals.AMP);
            }
          case 81: break;
          case 22: 
            { return newToken(Terminals.CARET);
            }
          case 82: break;
          case 23: 
            { return newToken(Terminals.PIPE);
            }
          case 83: break;
          case 24: 
            { return newToken(Terminals.QUESTION);
            }
          case 84: break;
          case 25: 
            { return newToken(Terminals.COLON);
            }
          case 85: break;
          case 26: 
            { return newToken(Terminals.COMMA);
            }
          case 86: break;
          case 27: 
            { return newToken(Terminals.SEMICOLON);
            }
          case 87: break;
          case 28: 
            { return newToken(Terminals.NUM, new Long(yytext()));
            }
          case 88: break;
          case 29: 
            { return newToken(Terminals.ASG_OP, yytext());
            }
          case 89: break;
          case 30: 
            { return newToken(Terminals.INCR);
            }
          case 90: break;
          case 31: 
            { return newToken(Terminals.DECR);
            }
          case 91: break;
          case 32: 
            { return newToken(Terminals.ARROW);
            }
          case 92: break;
          case 33: 
            { return newToken(Terminals.SHR);
            }
          case 93: break;
          case 34: 
            { return newToken(Terminals.GE);
            }
          case 94: break;
          case 35: 
            { return newToken(Terminals.NEQ);
            }
          case 95: break;
          case 36: 
            { return newToken(Terminals.IF);
            }
          case 96: break;
          case 37: 
            { return newToken(Terminals.SHL);
            }
          case 97: break;
          case 38: 
            { return newToken(Terminals.LE);
            }
          case 98: break;
          case 39: 
            { return newToken(Terminals.EQ);
            }
          case 99: break;
          case 40: 
            { return newToken(Terminals.AND);
            }
          case 100: break;
          case 41: 
            { return newToken(Terminals.OR);
            }
          case 101: break;
          case 42: 
            { return newToken(Terminals.DO);
            }
          case 102: break;
          case 43: 
            { return newToken(Terminals.INT);
            }
          case 103: break;
          case 44: 
            { return newToken(Terminals.FOR);
            }
          case 104: break;
          case 45: 
            { return newToken(Terminals.ENUM);
            }
          case 105: break;
          case 46: 
            { return newToken(Terminals.ELSE);
            }
          case 106: break;
          case 47: 
            { return newToken(Terminals.VOID);
            }
          case 107: break;
          case 48: 
            { return newToken(Terminals.CHAR);
            }
          case 108: break;
          case 49: 
            { return newToken(Terminals.LONG);
            }
          case 109: break;
          case 50: 
            { return newToken(Terminals.SHORT);
            }
          case 110: break;
          case 51: 
            { return newToken(Terminals.UNION);
            }
          case 111: break;
          case 52: 
            { return newToken(Terminals.BREAK);
            }
          case 112: break;
          case 53: 
            { return newToken(Terminals.WHILE);
            }
          case 113: break;
          case 54: 
            { return newToken(Terminals.SIZEOF);
            }
          case 114: break;
          case 55: 
            { return newToken(Terminals.SIGNED);
            }
          case 115: break;
          case 56: 
            { return newToken(Terminals.STRUCT);
            }
          case 116: break;
          case 57: 
            { return newToken(Terminals.RETURN);
            }
          case 117: break;
          case 58: 
            { return newToken(Terminals.TYPEDEF);
            }
          case 118: break;
          case 59: 
            { return newToken(Terminals.CONTINUE);
            }
          case 119: break;
          case 60: 
            { return newToken(Terminals.UNSIGNED);
            }
          case 120: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
